apiVersion: v1
kind: Secret
metadata:
  name: github-runner-secret
  namespace: cicd
type: Opaque
stringData:
  # INSERISCI QUI IL TOKEN TRAMITE KUBECTL, NON COMMITTARE QUESTO FILE CON IL TOKEN REALE
  RUNNER_TOKEN: "YOUR_GITHUB_RUNNER_TOKEN"
